(parse-assert-equal "1337" (term 1337))
(parse-assert-equal "-1337" (term -1337))
(parse-assert-equal "+12.3" (term 12.3))
(parse-assert-equal "-12.3" (term -12.3))
(parse-assert-equal "(1 2)" (term (1 2)))
(parse-assert-equal "(1 abc/fg)" (term (1 abc/fg)))
(parse-assert-equal "(1\"gfgf\")" (term (1 "gfgf")))
(parse-assert-equal "(\"gfgf\"(123))" (term ("gfgf" (123))))
(parse-assert-equal "((a b c) (1 2 3))" (term ((a b c) (1 2 3))))
(parse-assert-equal "#true" (term #t))
(parse-assert-equal "#f" (term #f))
